# 生产环境配置
spring:
  mvc:
    view:
      prefix: /WEB-INF/views/
      suffix: .jsp

  # 数据源
  datasource:
    url: jdbc:mysql:///merbac?serverTimezone=Asia/Shanghai&characterEncoding=utf8&useSSL=false
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: 123456
    hikari:
      auto-commit: true
      connection-timeout: 30000
      idle-timeout: 600000
      max-lifetime: 1800000
      connection-test-query: SELECT 1
      minimum-idle: 10
      maximum-pool-size: 10
      read-only: off

  # devtools
  devtools:
    livereload:
      enabled: false

# mybatis-plus
mybatis-plus:
  global-config:
    banner: off
  type-aliases-package: com.exam.entity
  configuration:
    map-underscore-to-camel-case: true

# PageHelper 分页插件
pagehelper:
  reasonable: false
  support-methods-arguments: true
  params: count=countSql
  row-bounds-with-count: true
  helper-dialect: mysql

# 服务器端口
server:
  port: 8080
  servlet:
    session:
      timeout: PT60M