server:
  port: 8400

spring:
  application:
    name: OES-APM-Spring-Admin
  security:
    user:
      name: oes
      password: 123456
  boot:
    admin:
      ui:
        title: ${spring.application.name}
  thymeleaf:
    cache: false