# 生产环境配置
server:
  # 端口
  port: 8080
  # 最大文件
  max-http-header-size: 5MB

# SpringMvc 配置
spring:
  # 数据源配置
  datasource:
    # driverClassName: com.p6spy.engine.spy.P6SpyDriver
    # url: jdbc:p6spy:mysql:///exam-system-test?serverTimezone=Asia/Shanghai&characterEncoding=utf8&useSSL=false
    # 数据库访问地址
    url: jdbc:mysql:///exam-system-test?serverTimezone=Asia/Shanghai&characterEncoding=utf8&useSSL=false
    #数据库账号
    username: root
    # 数据库密码
    password: 123456
    # 数据库连接至配置
    hikari:
      # 自动提交
      auto-commit: on
      # 连接超时时间
      connection-timeout: 30000
      # idle 超时
      idle-timeout: 600000
      # 最大生命周期
      max-lifetime: 1800000
      # 连接测试
      connection-test-query: SELECT 1
      # 最大线程池配置
      maximum-pool-size: 25
      # idle 最小值
      minimum-idle: 10
      # 关闭只读数据库配置
      read-only: off

  # 线程池配置
  task:
    execution:
      pool:
        # 核心数
        core-size: 10
        # 最大数量
        max-size: 30
        # 保持时间 - 60秒
        keep-alive: 60s
        # 队列大小
        queue-capacity: 50
        # 线程池名称
      thread-name-prefix: OES-pool-task-
    scheduling:
      # 定时任务线程池名称
      thread-name-prefix: OES-scheduling-
      # 池大小
      pool:
        size: 2

  redis:
    # 主机地址
    host: localhost
    # 端口
    port: 6379
    # 密码
    password:
    # 连接超时时间（记得添加单位，Duration）
    timeout: 2000ms
    # Redis默认情况下有16个分片，这里配置具体使用的分片
    database: 0
    lettuce:
      pool:
        # 连接池最大连接数（使用负值表示没有限制） 默认 8
        max-active: 8
        # 连接池最大阻塞等待时间（使用负值表示没有限制） 默认 -1
        max-wait: -1ms
        # 连接池中的最大空闲连接 默认 8
        max-idle: 8
        # 连接池中的最小空闲连接 默认 0
        min-idle: 0

  resources:
    static-locations: classpath:/static/
  mvc:
    static-path-pattern: /static/**

  # 分布式 session 配置
  session:
    store-type: redis
    # session 持久化前缀
    redis:
      # session 持久化命名空间
      namespace: oes:session
    # 过期时间 3小时
    timeout: PT3H

  jackson:
    date-format: yyyy-MM-dd HH:mm:ss

# MyBatisPlus 配置
mybatis-plus:
  # 全局配置
  global-config:
    # 关闭 MyBatisPlus 的 banner
    banner: off
  # 实体类别名
  type-aliases-package: com.chachae.exam.common.model
  configuration:
    # 打开驼峰命名
    map-underscore-to-camel-case: on

# PageHelper 分页插件配置
pagehelper:
  reasonable: false
  support-methods-arguments: true
  params: count=countSql
  # 开启优化
  row-bounds-with-count: true
  # 数据库方言 - MySQL
  helper-dialect: mysql
