# 生产环境配置
server:
  port: 8080
  max-http-header-size: 5MB

spring:
  datasource:
    url: jdbc:mysql:///exam-system-test?serverTimezone=Asia/Shanghai&characterEncoding=utf8&useSSL=false
    username: root
    password: 123456
    hikari:
      auto-commit: on
      connection-timeout: 30000
      idle-timeout: 600000
      max-lifetime: 1800000
      connection-test-query: SELECT 1
      maximum-pool-size: 25
      minimum-idle: 10
      read-only: off

  task:
    execution:
      pool:
        core-size: 10
        max-size: 30
        keep-alive: 60s
        queue-capacity: 50
      thread-name-prefix: OES-pool-task-
    scheduling:
      thread-name-prefix: OES-scheduling-
      pool:
        size: 2

  redis:
    host: localhost
    port: 6379
    password:
    timeout: 2000ms
    database: 0
    lettuce:
      pool:
        max-active: 8
        max-wait: -1ms
        max-idle: 8
        min-idle: 0

  resources:
    static-locations: classpath:/static/
  mvc:
    static-path-pattern: /static/**

  # 分布式 session 配置
  session:
    store-type: redis
    redis:
      namespace: oes:session
    # 过期时间 2小时
    timeout: PT2H

  jackson:
    date-format: yyyy-MM-dd HH:mm:ss

# MyBatisPlus 配置
mybatis-plus:
  global-config:
    banner: off
  type-aliases-package: com.chachae.exam.common.model
  configuration:
    map-underscore-to-camel-case: on
