# Server
server:
  port: 8080

spring:
  application:
    name: OES-SERVER

  # DataSource
  datasource:
    url: jdbc:mysql://${mysql.url}:3306/oes?serverTimezone=Asia/Shanghai&characterEncoding=utf8&useSSL=false
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 123456
    hikari:
      auto-commit: on
      connection-timeout: 30000
      idle-timeout: 600000
      max-lifetime: 1800000
      connection-test-query: SELECT 1
      maximum-pool-size: 25
      minimum-idle: 10
      read-only: off
      pool-name: OESHikariPool

  # Task
  task:
    execution:
      pool:
        core-size: 10
        max-size: 30
        keep-alive: 60s
        queue-capacity: 50
      thread-name-prefix: OES-pool-task-
    scheduling:
      thread-name-prefix: OES-scheduling-
      pool:
        size: 2

  #Lettuce-Redis
  redis:
    host: ${redis.url}
    port: 6379
    password:
    timeout: 2000ms
    database: 0
    lettuce:
      pool:
        max-active: 8
        max-wait: -1ms
        max-idle: 8
        min-idle: 0

  # Resource
  resources:
    static-locations: classpath:/static/

  #SpringMvc
  mvc:
    static-path-pattern: /static/**

  # redis-session
  session:
    store-type: redis
    redis:
      namespace: oes:session
    timeout: PT2H

  # Jackson2
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8

  # Spring-Admin
  boot:
    admin:
      client:
        url: http://${spring-admin.url}:8400
        username: oes
        password: 123456
        instance:
          prefer-ip: true

#MyBatisPlus
mybatis-plus:
  global-config:
    banner: off
    db-config:
      id-type: auto
  type-aliases-package: com.chachae.exam.common.model
  configuration:
    map-underscore-to-camel-case: on
# Actuator
management:
  endpoints:
    web:
      exposure:
        include: '*'
  endpoint:
    health:
      show-details: ALWAYS